bandit:
  run: true
  disable:
    - B310
    - B311

pylint:
  run: false
  disable:
  - E1127  # not working with pandas label slice indexing :(

dodgy:
  run: true

frosted:
  run: true

mccabe:
  run: true

mypy:
  run: false

pep257:
  run: true

pep8:
  run: true

pydocstyle:
  run: true

pyflakes:
  run: true

pyroma:
  run: false

vulture:
  run: true

