bandit:
  run: false

pylint:
  run: false

dodgy:
  run: true

frosted:
  run: true

mccabe:
  run: true

mypy:
  run: true

pep257:
  run: true
  # disable:
  #   - D403  # Docstring capitalization buggy

pep8:
  run: true

pydocstyle:
  run: true

pyflakes:
  # Disable because no 2.7 support (print "hello" not working)
  run: false

pyroma:
  run: false

vulture:
  run: true

