bandit:
  # run it natively
  run: false

pylint:
  run: false

dodgy:
  run: true

frosted:
  run: true

mccabe:
  run: true

mypy:
  run: false

pep257:
  run: true
  disable:
    # D212 & D213 are mutually exclusive
    # Ref: http://www.pydocstyle.org/en/5.0.2/error_codes.html
    - D213

pep8:
  run: true

pydocstyle:
  run: true

pyflakes:
  run: true

pyroma:
  run: false

vulture:
  run: true

