bandit:
  run: true
  disable:
    - B311

pylint:
  run: false

dodgy:
  run: true

frosted:
  run: true

mccabe:
  run: true

mypy:
  run: true

pep257:
  run: true

pep8:
  run: true

pydocstyle:
  run: true

pyflakes:
  # Disable because no 2.7 support (print "hello" not working)
  run: false

pyroma:
  run: false

vulture:
  run: true

