bandit:
  # run it natively
  run: false

pylint:
  run: false

dodgy:
  run: true

frosted:
  run: true

mccabe:
  run: true

mypy:
  run: false

pep257:
  run: true

pep8:
  run: true

pydocstyle:
  run: true

pyflakes:
  run: true

pyroma:
  run: false

vulture:
  run: true

