# Travis CI config file

os: linux
dist: bionic
language: python

# Version
python:
  - "2.7"
#  - "3.4"
#  - "3.5"
  - "3.6"      # current default Python on Travis CI
#  - "3.7"
#  - "3.8"
#  - "3.8-dev"  # 3.8 development branch
#  - "nightly"  # nightly build

# Command to install dependencies
#install:
#  - pip install -r requirements.txt

# Command to run test
script:
  - pytest
