# Travis CI config file

os: linux
dist: bionic
language: python

# Version
python:
  - "2.7"
#  - "3.4"
#  - "3.5"
  - "3.6"      # current default Python on Travis CI
#  - "3.7"
#  - "3.8"
#  - "3.8-dev"  # 3.8 development branch
#  - "nightly"  # nightly build

# Command to install dependencies
install:
  - pip install -r requirements.txt

# Initial setup script
before_script:
  - 'bash pwd'
  - 'bash ls -la'
  - 'bash mkdir -p stock_db/test'
  - 'bash python get_yahoo_finance_data.py -c 1 -f stock_db/test.txt -d ./stock_db/test'

# Command to run test
script:
  - pytest
