# Travis CI config file

os: linux
dist: bionic
language: python

# Version
python:
  - "2.7"
#  - "3.4"
#  - "3.5"
  - "3.6"      # current default Python on Travis CI
#  - "3.7"
#  - "3.8"
#  - "3.8-dev"  # 3.8 development branch
#  - "nightly"  # nightly build

# Command to install python dependencies
install:
  - pip install -r requirements.txt

# Initial setup script to download a minimal stock database that will be used for testing
before_script: |
  mkdir -p stock_db/test &&
  python get_yahoo_finance_data.py --concurrent 1 --file stock_db/test.txt --dir ./stock_db/test --startdate 20000101 --verbose

# Command to run the tests
script:
  - pytest

after_success:
  - codecov  # submit coverage
